version: '3.8'

services:
  pocketbase:
    build:
      context: ./pocketbase
    container_name: noting_pb
    restart: unless-stopped
    volumes:
      - ./pb_data:/pb/pb_data
    ports:
      - "8090:8080"
