version: '3.8'

services:
  pocketbase:
    build:
      context: ./pocketbase
    container_name: noting_pb
    restart: unless-stopped
    working_dir: /pb
    volumes:
      - ./pb_data:/pb/pb_data
    ports:
      - "8090:8090"
    command: ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb/pb_data"]
